DAG integrity test - using DagBag
다음 정보를 얻을 수 있다

cycle 이 존재해 DAG를 로드하지 못하는 경우 exception 발생

```
[2023-01-28 07:09:05,079] {dagbag.py:450} ERROR - Failed to bag_dag: /opt/dags/tests/dag/../../dags/dag_cycle.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 438, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 465, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 473, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 78, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 64, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: dag_cycle. Faulty task: t3
```

동일한 DAG id 가 존재하는지 확인

```
[2023-01-28 07:20:33,972] {dagbag.py:506} ERROR - Exception bagging dag: dag_test1
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 497, in _bag_dag
    raise AirflowDagDuplicatedIdException(
airflow.exceptions.AirflowDagDuplicatedIdException: Ignoring DAG dag_test1 from /opt/dags/tests/dag/../../dags/dag_test_2.py - also found in /opt/dags/tests/dag/../../dags/dag_test_1.py
```

deprecated API 에 대한 warning 확인

```
/opt/dags/tests/dag/../../dags/dag_cycle.py:7: RemovedInAirflow3Warning: Function `days_ago` is deprecated and will be removed in Airflow 3.0. You can achieve equivalent behavior with `pendulum.today('UTC').add(days=-N, ...)`
    start_date=airflow.utils.dates.days_ago(3),

tests/dag/test_dag_integrity.py::test_dag_integrity
  /opt/dags/tests/dag/../../dags/dag_cycle.py:5: RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
```

DAG integrity test sqush